// Code generated by Godin v0.3.0.
// This file can be modified, it will NOT be overwritten by godin.

package endpoint

import (
    "context"
    "github.com/go-kit/kit/endpoint"

    "github.com/lukasjarosch/godin/examples/user/internal/service"
)


// CreateEndpoint provides service.Create() as general endpoint
// which can be used with arbitrary transport layers.
func CreateEndpoint(service service.User) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(CreateRequest)
		user, err := service.Create(ctx, req.Username, req.Email)

		return CreateResponse{
			User: user,
			Err:  err,
		}, err
	}
}
