// Code generated by Godin v0.3.0; DO NOT EDIT.

package endpoint

import (
	"context"
	"github.com/go-kit/kit/endpoint"
	service "github.com/lukasjarosch/godin/examples/user"
	godin "github.com/lukasjarosch/godin/pkg/middleware"
)

type Set struct {
	CreateEndpoint endpoint.Endpoint
}

func Endpoints(service service.user, duration metrics.Histogram, frequency metrics.Counter) Set {

	var create endpoint.Endpoint
	{
		create = CreateEndpoint(service)
		create = godin.LatencyMiddleware(duration, "Create")(create)
		create = godin.RequestFrequency(frequency, "Create")(create)
	}

	return Set{
		CreateEndpoint: createEndpoint,
	}
}
