// Code generated by Godin {{ .Godin.Version }}; DO NOT EDIT.
package amqp

import (
	"github.com/pkg/errors"
	"github.com/streadway/amqp"

	"github.com/go-godin/log"
	middleware "github.com/go-godin/middleware/amqp"
	"github.com/go-godin/rabbitmq"

    "{{ .Service.Module }}/internal/service"
    "{{ .Service.Module }}/internal/service/subscriber"
)

type SubscriberSet struct {
    {{- range .Service.Subscriber }}
    {{ untitle .Handler }} rabbitmq.Subscriber
	{{ end -}}
}

// Subscriptions will initialize all AMQP subscriptions
func Subscriptions(channel *amqp.Channel) SubscriberSet {
	return SubscriberSet{
    {{- range .Service.Subscriber }}
        {{ untitle .Handler }}: rabbitmq.NewSubscriber(channel, &rabbitmq.Subscription{
            Exchange: "{{ .Subscription.Exchange }}",
		    Topic: "{{ .Subscription.Topic }}",
            AutoAck:  {{ .Subscription.AutoAck }},
            Queue: rabbitmq.SubscriptionQueue{
                AutoDelete: {{ .Subscription.Queue.AutoDelete }},
                Durable:    {{ .Subscription.Queue.Durable }},
                Exclusive:  {{ .Subscription.Queue.Exclusive }},
                Name:       "{{ .Subscription.Queue.Name }}",
                NoWait:     {{ .Subscription.Queue.NoWait }},
            },
		}),
	{{ end }}
	}
}

{{- $serviceName := title .Service.Name -}}

{{- range .Service.Subscriber }}
func (ss SubscriberSet) {{ .Handler }}(logger log.Logger, usecase service.{{ $serviceName }}) error {
	handler := subscriber.{{ .Handler }}(logger, usecase)
	handler = middleware.Logging(logger, "{{ .Subscription.Topic }}", handler)
	handler = middleware.PrometheusInstrumentation("{{ .Subscription.Topic }}", handler)
	handler = middleware.RequestID(handler)

	if err := ss.{{ untitle .Handler }}.Subscribe(handler); err != nil {
		logger.Error("failed to subscribe to {{ .Subscription.Topic }}", "err", err, "transport", "AMQP")
		return errors.Wrap(err, "failed to subscribe to {{ .Subscription.Topic }}")
	}
	logger.Info(
		"subscribed to topic '{{ .Subscription.Topic }}'",
		"topic", ss.{{ untitle .Handler }}.Subscription.Topic,
		"queue", ss.{{ untitle .Handler }}.Subscription.Queue.Name,
		"exchange", ss.{{ untitle .Handler }}.Subscription.Exchange,
		"transport", "AMQP",
	)

	return nil
}
{{ end }}

// Shutdown will call Shutdown() on all registered subscriptions
func (ss SubscriberSet) Shutdown() (err error) {
	err = ss.userCreatedSubscriber.Shutdown()

	return err
}
