// Code generated by Godin v{{ .Godin.Version }}; DO NOT EDIT.

package endpoints

import (
    "context"
    "github.com/go-kit/kit/endpoint"

    service "{{ .Service.ImportPath }}"
)

type Set struct {
    {{ range .Service.Methods }}
        {{ .Name }}Endpoint endpoint.Endpoint
     {{- end }}
}

func Endpoints(service service.{{ .Service.Name }}) Set {
    {{ range .Service.Methods }}
    var {{ untitle .Name }} endpoint.Endpoint
    {
        {{ untitle .Name }} = {{ .Name }}Endpoint(service)
    }
    {{- end }}

    return Set{
        {{- range .Service.Methods }}
            {{ .Name }}Endpoint: {{ untitle .Name}}Endpoint,
        {{- end }}
    }
}

