// Code generated by Godin v{{ .Godin.Version }}; DO NOT EDIT.

package endpoint

import (
    "github.com/go-kit/kit/endpoint"

    godinMiddleware "github.com/lukasjarosch/godin/pkg/middleware"
    "{{ .Service.Module }}/internal/service"
)

type Set struct {
    {{ range .Service.Methods }}
        {{ .Name }}Endpoint endpoint.Endpoint
     {{- end }}
}

func Endpoints(service service.{{ title .Service.Name }}) Set {
    {{ range .Service.Methods }}
    var {{ untitle .Name }} endpoint.Endpoint
    {
        {{ untitle .Name }} = {{ .Name }}Endpoint(service)
        {{ untitle .Name }} = godinMiddleware.Prometheus("{{ .Name }}")({{ untitle .Name }})
    }
    {{- end }}

    return Set{
        {{- range .Service.Methods }}
            {{ .Name }}Endpoint: {{ untitle .Name}},
        {{- end }}
    }
}

