// Code generated by Godin v{{ .Godin.Version }}; DO NOT EDIT.

package endpoint

import (
    "github.com/go-kit/kit/endpoint"

    "github.com/go-godin/middleware"
    "{{ .Service.Module }}/internal/service"
	"github.com/go-godin/log"
)

type Set struct {
    {{ range .Service.Methods }}
        {{ .Name }}Endpoint endpoint.Endpoint
     {{- end }}
}

func Endpoints(service service.{{ title .Service.Name }}, logger log.Logger) Set {
    {{ range .Service.Methods }}
    var {{ untitle .Name }} endpoint.Endpoint
    {
        {{ untitle .Name }} = {{ .Name }}Endpoint(service)
        {{ untitle .Name }} = middleware.Prometheus("{{ .Name }}")({{ untitle .Name }})
        {{ untitle .Name }} = middleware.Logging(logger, "{{ .Name }}")({{ untitle .Name }})
        {{ untitle .Name }} = middleware.RequestID()({{ untitle .Name }})
    }
    {{- end }}

    return Set{
        {{- range .Service.Methods }}
            {{ .Name }}Endpoint: {{ untitle .Name}},
        {{- end }}
    }
}

