// Code generated by Godin v{{ .Godin.Version }}; DO NOT EDIT.

package endpoint

import (
    "context"
    "github.com/go-kit/kit/endpoint"

    service "{{ .Service.ImportPath }}"
)

{{ range .Service.Methods }}
{{ template "endpoint" . }}
{{ end }}