// Code generated by Godin v{{ .Godin.Version }}.
// This file can be modified, it will NOT be overwritten by godin.

package endpoint

import (
    "context"
    "github.com/go-kit/kit/endpoint"

    service "{{ .Service.Module }}"
)

{{ range .Service.Methods }}
{{ template "endpoint" . }}
{{ end }}