// Code generated by Godin v{{ .Godin.Version }}; DO NOT EDIT.

package endpoint

import (
    "{{ .Service.Module }}/internal/service"
)

type (
{{ range .Service.Methods }}
{{ template "request" . }}
{{ template "response" . }}
{{ end }}
)

// Implement the Failer interface for all responses
{{- range .Service.Methods }}
func (resp {{ .Response }}) Failed() error { return resp.Err }
{{- end }}
